name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for pylint
      uses: dtenenba/GitHub-Action-for-pylint@0.7.2
      with: {"args": "pip install . ;pip install -r requirements-test.txt; echo -e '\n\n\nPYLINT OUTPUT STARTS HERE:\n\n\n' ; pylint --exit-zero -j 0 **/*.py"}
    - name: build dist
      run: rm -rf dist/* && python setup.py sdist
    - name: publish package to test
      run: pip install twine;/usr/local/bin/twine upload --repository-url https://test.pypi.org/legacy/ -u __token__ -p  ${{ secrets.test_pypi_password }} --skip-existing dist/*
    - name: publish package to prod
      # TODO change ci-dev to master below:
      if: github.ref == 'ci-dev'
      run: twine upload --repository-url https://upload.pypi.org/legacy/ -u __token__ -p  ${{ secrets.pypi_password }} --skip-existing dist/*
