name: CI

on: [push]

jobs:
  build:
    container: python:3.8.0

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: install
      run: |
        apt-get update -y
        apt-get install -y unixodbc-dev
        pip install --user .
        pip install --user pylint
    - name: pylint
      run: ~/.local/bin/pylint --exit-zero -j 0 **/*.py
    - name: run unit tests
      run: |
        python unit_tests.py
    - name: build dist
      run: rm -rf dist/* && python setup.py sdist
    - name: publish package to test
      run: |
        pip install --user twine
        python -m twine upload --repository-url https://test.pypi.org/legacy/ -u __token__ -p  ${{ secrets.test_pypi_password }} --skip-existing dist/*
    - name: publish package to prod
      if: github.ref == 'refs/heads/master'
      run:  |
        python -m twine upload --repository-url https://upload.pypi.org/legacy/ -u __token__ -p  ${{ secrets.pypi_password }} --skip-existing dist/*
