name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for pylint
      uses: dtenenba/GitHub-Action-for-pylint@0.7.0
      with: {"args": "pip install . ; pylint **/*.py | true"}
